version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      # 🟡 ИСПРАВЛЕНО: Добавлен пароль в connection string
      # БЫЛО: DB_URL: postgres://postgres@postgres:5432/urlshortener
      DB_URL: postgres://postgres:password@postgres:5432/urlshortener?sslmode=disable
      APP_BASE_URL: http://localhost:8080
    volumes:
      - ./migrations:/app/migrations  # Изменен путь к миграциям
    depends_on:
      - postgres
    restart: unless-stopped
    # 🟡 ДОБАВЛЕНО: Healthcheck для улучшения надежности
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: